export default [
    "Introduction",
    "Learn and Explore HTML as a Beginner",
    "explore CSS",
    "Git, source control, GitHub, and hosting",
    "Project foldering structure and website design planning",
    "Design a portfolio website",
    "Design a blog website",
    "Design a ecommerce website with SCSS",
    "Responsive website",
    "Navbar, Dropdown navbar, Jumbo navbar, Sidebar",
    "Figma to html with Bootstrap css",
    "PSD to html with tailwind css",
    "jQuery: selection, plugin installation",
    "Basic PHP: Input, Output, variables, constant, arithmetic operators, increment decrement",
    "Basic PHP: condional operators, conditions, switch",
    "Basic PHP: array, array methods",
    "Basic PHP: multi dimentional array",
    "Basic PHP: Loop, function",
    "Basic PHP: OOP",
    "PHP super global variales",
    "PHP Form handling",
    "Laravel Installation: project overview",
    "Frontend setup, database and auth setup",
    "route, controller, model, basic CRUD and contact message store",
    "Backend setup",
    "contact message view, user management, form validatioan, store data",
    "AJAX, user update, user role setup, route middleware",
    "Product management: categroy, subcategory, product create",
    "product list, edit, delete, frontend product show",
    "Cart management",
    "Shipping, payment gateway",
    "order management, order details, status change, print invoice",
    "invoice mail",
    "User history, and personal profile",
    "data table advanced",
    "vue js basic",
    "fiverr",
    "freelancer",
    "upwork",
    "Exam, Cirtificate Providing and Future Guide Line" 
];