export default [    
    "Introduction, Web & Internet Fundamentals",
    "HTML, Everything needs to be learned",
    "CSS Basics",
    "Css Layout",
    "Responsive Design",
    "Portfolio Design",
    "Learn Git & GitHub, Version Controlling & Deployment",
    "Assignment 01",
    "PSD To HTML",
    "Figma to HTML",
    "XD to HTML",
    "Facebook Desktop UI Design - ( Part 01 - 04 )",
    "Programming Basics",
    "Data Types, Math & Date Objects in JavaScript",
    "Condition and Logic",
    "Loops in JavaScript",
    "Js Number, String, Boolean & their methods",
    "JS Array & Array Methods",
    "JavaScript Object & Function",
    "Dom Manipulation",
    "Event Handling",
    "Bulding a TODO App",
    "Task Management APP",
    "Making a calculator",
    "Building a Weather app using external API"
];